mode: SIMULATION  # Options: SIMULATION or LIVE
pairs:
  - symbol: BTC/USD
  - symbol: ETH/USD
exchanges:
  - name: kraken
    maker_fee: 0.06  # Maker fee (in %)
    taker_fee: 0.16  # Taker fee (in %)
  - name: coinbase
    maker_fee: 0.60  # Maker fee (in %)
    taker_fee: 0.40  # Taker fee (in %)
logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR
  output: file  # Options: console or file
  filename: logs/app.log
