version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    volumes:
      - ./logs:/app/dashboard/logs

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dashboard
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
